version: '3.8'

services:
  consultorio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aura-salud-demo
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
